package org.agmip.ace;

public enum AceEventType {
    ACE_PLANTING_EVENT,
    ACE_IRRIGATION_EVENT,
    ACE_FERTILIZER_EVENT,
    ACE_TILLAGE_EVENT,
    ACE_ORGANIC_MATTER_EVENT,
    ACE_HARVEST_EVENT,
    ACE_MULCH_ADD_EVENT,
    ACE_MULCH_REMOVE_EVENT,
    ACE_INVALID_EVENT
}